In [1]:
import numpy as np

In [5]:
# create an array from a list
a=np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [13]:
# create an array with evenly spaced values
b=np.arange(0,10,2) # Values from 0 to 10 with step 2
print("Array b:",b)

Array b: [0 2 4 6 8]


In [17]:
# create an array with linearly spaced values
c=np.linspace(0,1,5) # 5 values evenly spaced between 0 and 1
print("Array c:",c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [25]:
# create an array filled with zeros
d=np.zeros((2,3)) #2*3 array of zeros
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# create an array filled with ones
e=np.ones((3,4)) # 3*4 array of ones
print('Array e:\n',e)

Array e:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
# create an identity matrix
f=np.eye(4) # 4*4 identity matrix
print('Array f:\n',f)

Array f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Array Manipulation Functions

In [37]:
# Reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3)) # Reshape to 1*3
print('Reshaped Array:',reshaped)

Reshaped Array: [[1 2 3]]


In [41]:
# Flatten an array
b1=np.array([[1,2],[3,4]])
flattened=np.ravel(b1) # Flatten to 1D array
print('Flattened array:',flattened)

Flattened array: [1 2 3 4]


In [43]:
# Transpose an Array
c1=np.array([[1,2],[3,4]])
transposed=np.transpose(c1) # Transpose the array 
print('Transpose Array:',transposed)

Transpose Array: [[1 3]
 [2 4]]


In [45]:
# Stack arrays vertically
d1=np.array([1,2])
d2=np.array([3,4])
stacked=np.vstack([d1,d2])
print('Stacked arrays:\n',stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


# 3. Mathematical Functions

In [48]:
# Add two arrays
g=np.array([1,2,3,4])
added=np.add(g,2) # Add 2 to each other
print('Added 2 to g:',added)

Added 2 to g: [3 4 5 6]


In [52]:
# square each element
sqrt_val=np.sqrt(g) # Square root of each element
print('Square root of g:',sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [54]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [56]:
# Dot product of two arrays
a2=np.array([1,2,3])
dot_product=np.dot(a2,g) # Dot product of a and g
print('Dot product of a and g:',dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [58]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [60]:
a3=np.array([1,2,3])
dot_product=np.dot(a1,a) # Dot product of a and g
print('Dot product of a1 and a:',dot_product)

Dot product of a1 and a: 14


# 4. Statistical Functions

In [63]:
s=np.array([1,2,3,4])
mean=np.mean(s)
print('Mean of s:',mean)

Mean of s: 2.5


In [65]:
# Standard deviation of an array
std_dev=np.std(s)
print('Standard deviation of s:',std_dev)

Standard deviation of s: 1.118033988749895


In [67]:
# Minimum element of an array
maximum=np.max(s)
print('Max of s:',maximum)

Max of s: 4


In [69]:
# Minimum of elements of an array
minimum=np.min(s)
print('Min of s:',minimum)

Min of s: 1


# 5. Linear Algebra Functions

In [74]:
# create a matrix
matrix=np.array([[1,2],[3,4]])

In [76]:
# Determinant of matrix
determinant =np.linalg.det(matrix)
print('Determination of matrix:',determinant)

Determination of matrix: -2.0000000000000004


In [80]:
# Inverse of a matrix
inverse=np.linalg.inv(matrix)
print('Inverse of matrix:\n',inverse)
      

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 6. Random Sampling Functions

In [84]:
# Generate random values between 0 and 1
random_vals=np.random.rand(3) # Array of 3 random values between 0 and 1
print('Random values:',random_vals)

Random values; [0.17905636 0.93610393 0.06852704]


In [86]:
random_vals=np.random.rand(2)
print('random values:',random_vals)

random values: [0.46847661 0.057656  ]


In [91]:
# Set speed for reproducibility
np.random.seed(0)
# Generate random values between 0 and 1
random_vals=np.random.rand(3) # Array of 3 random values between 0 and 1
print('Random values:',random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [101]:
# Generate Random Integers
rand_ints=np.random.randint(0,10,size=5) # random integers between 0 and 1
print('Random integers:',rand_ints)

Random integers: [8 1 6 7 7]


In [110]:
# Set seed for reproducibility
np.random.seed(0)
# Generate random integers
rand_ints=np.random.randint(0,10,size=5) # Random integers between 0 and 10
print('random integers :',rand_ints)

random integers : [5 0 3 3 7]


# 7. Boolean & Logical Functions

In [113]:
# check if all elements are true
# all
logical_test=np.array([True,False,True])
all_true=np.all(logical_test) # chack if all are True
print('All elements True:',all_true)

All elements True: False


In [115]:
# check if all elements are true

logical_test=np.array([True,False,True])
all_true=np.all(logical_test) # chack if all are True
print('All elements True:',all_true)

All elements True: False


In [117]:
# check if all elements are true
# all
logical_test=np.array([False,False,False])
all_true=np.all(logical_test) # chack if all are True
print('All elements True:',all_true)

All elements True: False


In [119]:
# check if any elements are True
# any
any_true=np.any(logical_test) # check if any are True
print('Any elements True:',any_true)

Any elements True: False


# 8. Set Operations

In [122]:
# Intersection of two arrays
set_a=np.array([1,2,3,4])
set_b=np.array([3,4,5,6])
intersection=np.intersect1d(set_a,set_b)
print('Intersection of a and b:',intersection)

Intersection of a and b: [3 4]


In [124]:
# Union of two arrays
union=np.union1d(set_a,set_b)
print('union of a and b:',union)

union of a and b: [1 2 3 4 5 6]


#  9. Array Attribute Functions

In [128]:
# Array attributes
a=np.array([1,2,3])
shape=a.shape # shape of the array
size=a.size # Number of elements
dimensions=a.ndim # Number of dimensions
dtype=a.dtype # data type of the array


print('shape of a:',shape)
print('size of a:',size)
print('Number of dimensions of a:',dimensions)
print('data type of a:',dtype)

shape of a: (3,)
size of a: 3
Number of dimensions of a: 1
data type of a: int32


# 10.Other Functions

In [131]:
# create a copy of an array
a=np.array([1,2,3])
copied_array=np.copy(a) # create a copy of array a
print('Copied array:',copied_array)

Copied array: [1 2 3]


In [133]:
# Size in bytes of an array
array_size_in_bytes= a.nbytes # size in bytes
print('Size of a in bytes:',array_size_in_bytes)

Size of a in bytes: 12


In [135]:
# Check if two arrays share memory
shared=np.shares_memory(a,copied_array) # check if arrays share memory
print('Do a and copied_array share memory?',shared)

Do a and copied_array share memory? False
